language: ruby
cache:
  - bundler
  - yarn
notifications:
  email: false
  slack:
    secure: D/HmCRi5MH7miTew1ybp75pHtF9YOfA3wLfedzcEyXMihVZXCRVHkvR2uOmcR8rL2NgExV+foWoxueIzxWNBgr8ljWi+AiB8OD7ZGQfqn4L5c9JUPAvNgmoZu05M0o7tRGXGnqN+38MydiPxbUPe5LWvo493XkJWYm9smaifrdQ=
services:
  - postgresql
sudo: required
before_install:
  - gem update --system
  - gem install bundler
  - nvm install
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.5.1-1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version
before_script:
  - psql -c 'create database denali_test;' -U postgres
script:
  - yarn
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rails test
  - bundle exec rake brakeman:check
