grandtetonnationalpark:
  name: "Grand Teton National Park"
  id: "236820032999267"
nationalelkrefuge:
  name: "National Elk Refuge"
  id: "155137617829904"
jackson:
  name: "Jackson, Wyoming"
  id: "200455076657822"
wyoming:
  name: "Wyoming"
  id: "282553615113028"
sanfrancisco:
  name: "San Francisco, California"
  id: "220512791294212"
