bears:
  - https://www.flickr.com/groups/2176466@N24/
  - https://www.flickr.com/groups/bearsjustbears/
  - https://www.flickr.com/groups/wildbears/
bison:
  - https://www.flickr.com/groups/americanbison/
  - https://www.flickr.com/groups/1182213@N23/
  - https://www.flickr.com/groups/buffalobison/
blackandwhite:
  - https://www.flickr.com/groups/blackandwhitertw/
  - https://www.flickr.com/groups/bwdigital/
  - https://www.flickr.com/groups/bw_photo-group/
  - https://www.flickr.com/groups/blackandwhitemao/
  - https://www.flickr.com/groups/blackandwhiteandblackandwhite/
fujifilm:
  - https://www.flickr.com/groups/fujifilmfolks/
  - https://www.flickr.com/groups/fujixseries/
fujifilmx100f:
  - https://www.flickr.com/groups/x100f-acros/
  - https://www.flickr.com/groups/3112097@N22/
  - https://www.flickr.com/groups/3158953@N24/
fujifilmxt2:
  - https://www.flickr.com/groups/fujifilm_x-t2_users/
  - https://www.flickr.com/groups/fujifilmxt2/
fujifilmxt3:
  - https://www.flickr.com/groups/fujifilm_x-t3/
  - https://www.flickr.com/groups/4528784@N25/
grandtetonnationalpark:
  - https://www.flickr.com/groups/usnationalparks/
  - https://www.flickr.com/groups/1512748@N21/
  - https://www.flickr.com/groups/535883@N22/
landscapes:
  - https://www.flickr.com/groups/2297498@N20/
  - https://www.flickr.com/groups/worldphotos/
  - https://www.flickr.com/groups/landscapephotographymagazine/
  - https://www.flickr.com/groups/worldlandscapes/
nationalparks:
  - https://www.flickr.com/groups/usnationalparks/
  - https://www.flickr.com/groups/2203118@N25/
  - https://www.flickr.com/groups/usnationalparksandplaces/
  - https://www.flickr.com/groups/bestofnps/
  - https://www.flickr.com/groups/usnp/
nationalelkrefuge:
  - https://www.flickr.com/groups/535883@N22/
streets:
  - https://www.flickr.com/groups/realstreet/
  - https://www.flickr.com/groups/streetphotographyblog/
  - https://www.flickr.com/groups/street_photography_and_street_photographers/
  - https://www.flickr.com/groups/97329809@N00/
wildlife:
  - https://www.flickr.com/groups/worldphotos/
  - https://www.flickr.com/groups/wildlifephotographerscentral/
  - https://www.flickr.com/groups/wildlife_and_habitats/
  - https://www.flickr.com/groups/24549263@N00/
  - https://www.flickr.com/groups/wildlife_unlimited/
  - https://www.flickr.com/groups/wildlife_of_the_west/
  - https://www.flickr.com/groups/1751464@N21/
  - https://www.flickr.com/groups/1841383@N22/
  - https://www.flickr.com/groups/wildlifeandnaturephotography/
wyoming:
  - https://www.flickr.com/groups/wyoming/
  - https://www.flickr.com/groups/53031223@N00/
  - https://www.flickr.com/groups/1148888@N20/
