instagram:
  all:
    - lensculture
    - myfeatureshoot
    - somewheremagazine
  apple:
    - iphoneography
    - iphoneonly
    - iphonephotography
    - shotoniphone
  architecture:
    - archdaily
    - archidaily
    - archilovers
    - architecturelovers
    - architecturephotography
    - architectureporn
    - architexture
  blackandwhite:
    - blackandwhitephoto
    - blackandwhitephotography
    - blancoynegro
    - bnw
    - bnw_captures
    - bnw_demand
    - bnw_life
    - bnw_magazine
    - bnw_planet
    - bnw_society
    - bnwmood
    - bw
    - bw_lover
    - bw_photooftheday
    - bw_society
    - bwstyles_gf
    - igersbnw
    - insta_bw
    - instablackandwhite
    - monoart
    - monochromatic
    - monochrome
    - noiretblanc
  caracas:
    - ccs
    - ig_caracas
  cars:
    - carinstagram
    - carporn
    - carsofinstagram
    - carstagram
    - igcars
    - instacars
  cats:
    - catlover
    - catlovers
    - catoftheday
    - cats
    - cats_of_instagram
    - catsagram
    - catsofig
    - catsofinstagram
    - catstagram
    - ilovemycat
    - instacat
    - instacats
    - instagramcats
  chattanooga:
    - nooga
    - noogagram
  cityscape:
    - citylife
    - cityphotography
    - cityscape
    - cityview
    - skyline
  ciudaddemexico:
    - cdmx
    - ciudaddemexico
    - df
    - igerscdmx
    - mexicocity
    - mexicodf
  classiccars:
    - drivetastefully
    - retrocars
    - vintagecars
  districtofcolumbia:
    - acreativedc
    - dcitystyle
    - districtofcolumbia
    - exploredc
    - exposeddc
    - fotodc
    - igdc
    - igersdc
    - mydccool
    - streetmeetdc
    - walkwithlocals
    - washingtondaily
    - washingtondc
  film:
    - analogphotography
    - believeinfilm
    - filmisnotdead
    - filmphotography
    - ishootfilm
    - shootfilm
    - thefilmcommunity
  findyourpark: &findyourpark
    - findyourpark
    - goparks
  fujifilm:
    - fuji
    - fujifeed
    - fujifilm
    - fujifilm_xseries
    - fujifilmx_us
    - fujifilmxseries
    - fujiframez
    - fujilove
    - fujixclub
    - fujixseries
    - myfujifilm
  landscape:
    - landscape_captures
    - landscape_lovers
    - landscapelovers
    - landscapephotography
    - landscapes
  lasvegas:
    - lasvegasstrip
    - sincity
    - vegas
    - vegasbaby
  leica:
    - 🔴
    - leica
    - leicacamera
    - leicam
    - leicaphoto
    - leicaphotography
  mexico:
    - ig_mexico
    - igersmexico
    - mexico
    - mexico_maravilloso
    - mexigers
    - mextagram
    - vive_mexico
  nationalairandspacemuseum:
    - airandspace
  nationalgalleryofart:
    - myngadc
  nationalparks: *findyourpark
  newyorkcity:
    - icapture_nyc
    - ig_great_shots_nyc
    - ig_nycity
    - igersofnyc
    - instagramnyc
    - made_in_ny
    - newyork_ig
    - newyork_instagram
    - newyorkcity
    - newyorknewyork
    - ny
    - nycprimeshot
    - unlimitednewyork
    - what_i_saw_in_nyc
  pittsburgh:
    - '412'
    - pgh
    - pghcreative
    - steelcitygrammers
  scotland:
    - ig_scotland
    - insta_scotland
    - instascotland
    - visitscotland
  streetphotography:
    - everybodystreet
    - ig_street
    - lensculture
    - lensculturestreets
    - magnumphotos
    - seemycity
    - spicollective
    - street_photo_club
    - streetart
    - streetlife
    - streetlife_award
    - streetmagazine
    - streetmagazines
    - streetphoto
    - streetphotographer
    - streetphotographers
    - streets_vision
    - streetshot
    - urbanandstreet
  tennessee:
    - instagramtennessee
    - tn
  venezuela:
    - elnacionalweb
    - igersvenezuela
    - instavenezuela
    - vzla
tumblr:
  all:
    - 'original photographers'
    - 'photographers on tumblr'
