instagram:
  fujifilm:
    - fujifeed
    - fujifilmx_us
    - fujilove
    - fujifilm_xseries
  blackandwhite:
    - bnw
    - bw
    - blackandwhitephotography
    - monochrome
    - bnw_society
    - bnw_captures
    - bnw_life
  streetphotography:
    - spicollective
    - ig_street
    - everybodystreet
    - streetphoto
    - streetlife
    - streetphotographers
  scotland:
    - visitscotland
    - instascotland
    - insta_scotland
    - ig_scotland
  districtofcolumbia:
    - igdc
    - washingtondaily
    - exploredc
    - igersdc
    - walkwithlocals
    - mydccool
    - fotodc
    - dcitystyle
    - acreativedc
    - exposeddc
  cats:
    - catsofinstagram
    - catstagram
    - instacat
  mexico:
    - mextagram
    - mexigers
    - ig_mexico
    - mexico_maravilloso
  ciudaddemexico:
    - cdmx
    - mexicodf
    - mexicocity
    - igerscdmx
  newyorkcity:
    - newyork_instagram
    - instagramnyc
    - nycprimeshot
    - ig_nycity
    - what_i_saw_in_nyc
    - newyork_ig
  landscape:
    - landscape_lovers
    - landscapephotography
  cityscape:
    - citylife
    - cityview
  architecture:
    - archilovers
    - architecturelovers
    - architectureporn
  apple:
    - shotoniphone
  pittsburgh:
    - 412
    - pgh
    - steelcitygrammers
    - pghcreative
  leica:
    - leicacamera
    - leicam
    - leicaphoto
    - leicaphotography
    - 🔴
  all:
    - myfeatureshoot
    - somewheremagazine
    - lensculture
tumblr:
  all:
    - 'original photographers'
    - 'photographers on tumblr'
    - lensblr
