instagram:
  apple:
    - iphonephoto
    - iphonephotograph
    - iphonephotographer
    - iphonephotos
    - iphonepic
    - shotoniphone
  astrophotography:
    - astrophoto
    - astrophotography
    - milkywaychasers
    - nightscape
    - nightscapes
  baldeagle:
    - baldeagle
  baltimore:
    - baltimore
    - bmore
    - charmcity
    - baltimoremd
  birds:
    - birding
    - birdphotography
    - birdsofinstagram
    - ornithology
    - wildbirds
  bison:
    - bison
    - americanbison
  caracas:
    - caracas
    - caracascity
    - caracashermosa
    - caracasvenezuela
    - caracaswalk
    - igerscaracas
  cats:
    - cats
    - catsagram
    - catscatscats
    - catsgram
    - catslife
    - catsofig
    - catsofinsta
    - catsofinstagram
    - catstagram
    - catstuff
    - cutecats
    - instacat
    - instacats
    - instagramcats
  chattanooga:
    - chattanooga
    - chattanoogatn
    - chattanoogaphotographer
    - chattanoogatennessee
    - chattanoogaphotography
  cityscapes:
    - cityexplore
    - cityphotography
    - cityscapephotography
    - cityscapes
    - cityscapesphotography
    - cityshots
    - cityskyline
  ciudaddemexico:
    - cdmx
    - ciudaddemexico
    - instacdmx
    - mexicocity
    - mexicodf
  coffee:
    - coffee
    - coffeeholic
    - coffeegram
    - coffeelover
    - coffeelife
    - coffeetime
    - coffeedaily
    - instacoffee
  concerts:
    - bandphotographer
    - concert
    - concertlive
    - concertphotographer
    - concertphotography
    - concertphotos
    - concerts
    - liveconcert
    - liveconcertphotography
    - livemusic
    - livemusicphotography
    - musicphotographer
  districtofcolumbia:
    - dc_spc
    - dcfocused
    - dcitystyle
    - dclife
    - districtofcolumbia
    - exploredc
    - fotodc
    - ilovedc
    - mydccool
    - thedistrict
    - walkwithlocals
    - washingtondaily
    - washingtondc
    - washmagphoto
  dogs:
    - cutedogs
    - doggy
    - doglifestyle
    - dogs
    - dogsofig
    - dogsofinstagram
    - dogstagram
    - dogstagram
    - igdogs
    - ilovedogs
    - instadogs
  film:
    - analogphoto
    - believeinfilm
    - filmisnotdead
    - filmphotography
    - grainisgood
    - onfilm
    - shootfilm
    - shotonfilm
  fujifilm:
    - fujifeed
    - fujifilm
    - fujilove
    - fujix
    - fujixseries
  landscapes:
    - landscapecaptures
    - landscapephoto
    - landscapephotography
    - landscapeporn
    - landscapes
    - natgeolandscape
    - yourshotphotographer
  lasvegas:
    - lasvegasstrip
    - sincity
    - vegas
    - vegasbaby
  leica:
    - 🔴
    - leica
    - leicacamera
    - leicagram
    - leicam
    - leicaphoto
    - leicaphotography
    - leicaworld
  longexposure:
    - longexpo
    - longexposure
    - longexposurephotography
    - longexposureshots
  mexico:
    - ilovemexico
    - mejico
    - mexico
    - mexicolove
    - mexicomagico
    - mexicomaravilloso
    - vivamexico
  mobile:
    - mobilephotography
    - phonephotography
    - phoneshot
    - phoneographic
    - phoneography
    - phonephoto
  nationalairandspacemuseum:
    - airandspace
  nationalelkrefuge:
    - jacksonhole
    - staywild
  nationalgalleryofart:
    - myngadc
  nationalparks: &nationalparks
    - americasbestidea
    - encuentratuparque
    - findyourpark
    - goparks
    - nationalparks
    - nationalparkservice
    - optoutside
    - usinterior
  nationalmall: *nationalparks
  yosemitenationalpark: *nationalparks
  greatfallspark: *nationalparks
  grandtetonnationalpark:
    - grandteton
    - grandtetonnationalpark
    - gtnp
    - mygrandteton
    - tetons
    - jacksonhole
    - staywild
  yellowstonenationalpark:
    - yellowstone
    - yellowstonenationalpark
    - yellowstonenps
    - yellowstonepledge
  mountrainiernationalpark:
    - mountrainiernationalpark
    - mountrainiernps
    - mtrainiernationalpark
    - nrthwst
    - wanderwashington
  nationalportraitgallery:
    - mynpg
  newyorkcity: &nyc
    - igersnyc
    - ilovenyc
    - newyorkinstagram
    - newyorkphoto
    - nycityworld
    - nycspc
    - nyloveyou
    - topnewyorkphoto
  manhattan: *nyc
  brooklyn: *nyc
  queens: *nyc
  bronx: *nyc
  philadelphia:
    - cityofbrotherlylove
    - instadelphia
    - instaphilly
    - philadelphia
    - philadelphiaphotographer
    - phillygram
    - phillylove
    - visitphilly
  pittsburgh:
    - '412'
    - pgh
    - pghcreative
    - pittsburgh
    - pittsburghphotographer
    - pittsburghphotography
    - steelcitygrammers
  sanfrancisco:
    - alwayssf
    - citybythebay
    - igerssf
    - igsanfrancisco
    - onlyinsf
    - sanfrancisco
    - sf
    - streetsofsf
  seattle:
    - exploreseattle
    - seattle
    - seattlelife
    - seattlelove
    - seattlephotographer
    - seattlephotography
    - seattlewa
    - seattlewashington
    - visitseattle
  scotland:
    - igersscotland
    - lovescotland
    - scotland
    - scotlandphotography
    - scotlandshots
    - scotshots
  streets:
    - everybodystreet
    - lensculturestreets
    - lensonstreets
    - magnumphotos
    - spicollective
    - storyofthestreet
    - streetgram
    - streetphotography
    - streetphotographyinternational
    - thestreetphotographyhub
  tennessee:
    - instagramtennessee
    - tennesseephotographer
    - tennesseephotography
    - tn
  venezuela:
    - elnacionalweb
    - igersvenezuela
    - instavenezuela
    - venezuela
    - vzla
  wildlife:
    - animalplanet
    - bbcearth
    - natgeowild
    - wildlifephotographer
    - wildlifephotography
    - wildlifeplanet
  wyoming:
    - explorewyoming
    - thatswy
    - visitwyoming
    - wyoming
    - wyomingexplored
    - wyominglife
    - wyomingphotographer
