instagram:
  apple:
    - iphonephoto
    - iphonephotograph
    - iphonephotographer
    - iphonephotos
    - iphonepic
    - shotoniphone
  architecture:
    - amazingarchitecture
    - archilove
    - archiporn
    - architecture_lovers
    - architecturedaily
    - architecturedetails
    - architecturelover
    - architecturephotography
    - architectureporn
    - buildinglovers
    - lovearchitecture
  astrophotography:
    - astro_photography
    - astropgraphy
    - astrophoto
    - astrophotography
    - ig_astrophotography
    - natgeospace
    - nightimages
    - nightscaper
    - nightscapes
    - nightsky
    - nightskyphotography
    - starphotography
    - starscape
  birds:
    - best_birds_of_ig
    - birdlove
    - birds
    - birdslover
    - birdsofinstagram
    - birdsphotography
    - featheredfriends
    - ig_discover_birdslife
    - ornithology
    - wildbirds
  blackandwhite:
    - bandw
    - blackandwhite
    - blackandwhitephoto
    - blackandwhitephotograph
    - blackandwhitephotography
    - blackandwhitepics
    - bnw_planet
    - bnwcommunity
    - bnwlovers
    - bnwphotography
    - bwphotography
    - instablackandwhite
    - instabnw
  caracas:
    - caracas
    - caracascity
    - caracashermosa
    - caracasvenezuela
    - caracaswalk
    - igerscaracas
  cars:
    - cars
    - carsofinstagram
    - car
    - coolcars
    - dailycars
    - carlove
    - carlovers
    - lovethiscar
  cats:
    - cats
    - cats_of_instagram
    - catsagram
    - catscatscats
    - catsgram
    - catslife
    - catsofig
    - catsofinsta
    - catsofinstagram
    - catstagram
    - catstuff
    - cutecats
    - instacat
    - instacats
    - instagramcats
  chattanooga:
    - chattanooga
    - chattanoogatn
    - chattanoogaphotographer
    - chattanoogatennessee
    - chattanoogaphotography
  cityscapes:
    - cityexplore
    - cityphotography
    - cityscapephotography
    - cityscapes
    - cityscapes_unlimited
    - cityscapesphotography
    - cityshots
    - cityskyline
    - cityvibe
    - skylinephotography
  ciudaddemexico:
    - cdmx
    - ciudaddemexico
    - instacdmx
    - mexicocity
    - mexicodf
  coffee:
    - coffee
    - coffee_inst
    - coffeeholic
    - coffee_time
    - coffeegram
    - coffeelover
    - coffeelife
    - coffeetime
    - coffeedaily
    - instacoffee
  concerts:
    - bandphotographer
    - concert
    - concertlive
    - concertphotographer
    - concertphotography
    - concertphotos
    - concerts
    - liveconcert
    - liveconcertphotography
    - livemusic
    - livemusicphotography
    - musicphotographer
  districtofcolumbia:
    - dcchasers
    - dcfocused
    - dcitystyle
    - dclife
    - districtofcolumbia
    - exploredc
    - fotodc
    - igdc
    - ilovedc
    - mydccool
    - thedistrict
    - walkwithlocals
    - washingtondaily
    - washingtondc
    - washmagphoto
  dogs:
    - cutedogs
    - doggy
    - doglifestyle
    - dogs
    - dogsofig
    - dogsofinstagram
    - dogstagram
    - dogstagram
    - igdogs
    - ilovedogs
    - instadogs
  film:
    - analogphoto
    - believeinfilm
    - filmisnotdead
    - filmphotography
    - grainisgood
    - onfilm
    - shootfilm
    - shotonfilm
  fujifilm:
    - fuji_xseries
    - fujifeed
    - fujifilm
    - fujilove
    - fujix
    - fujixseries
    - fujixshooters
    - myfujilove
  fujifilmxt2:
    - fujifilmxt2
    - fujixt2
  fujifilmxt3:
    - fujifilmxt3
    - fujixt3
  fujifilmxh1:
    - fujifilmxh1
    - fujixh1
  fujifilmx100f:
    - fujifilmx100f
    - fujix100f
  landscapes:
    - igersnature
    - landscape
    - landscape_lover
    - landscape_photography
    - landscapeart
    - landscapecaptures
    - landscapehunter
    - landscapelovers
    - landscapephoto
    - landscapephotographer
    - landscapephotography
    - landscapes
    - lovelandscape
    - naturelandscape
    - naturephotography
  lasvegas:
    - lasvegasstrip
    - sincity
    - vegas
    - vegasbaby
  leica:
    - 🔴
    - leica
    - leicacamera
    - leicagram
    - leicam
    - leicaphoto
    - leicaphotography
    - leicaworld
  longexposure:
    - amazing_longexpo
    - long_exposure_pics
    - longexpo
    - longexpoelite
    - longexpohunter
    - longexposhots
    - longexposure
    - longexposure_shots
    - longexposureoftheday
    - longexposurephotography
    - longexposures
    - longexposureshots
    - slowshutter
    - slowshutterspeed
  magazines:
    - aintbadmagazine
    - aperturefoundation
    - archivecollectivemag
    - burnmagazine
    - foammagazine
    - gupmagazine
    - ifyouleave
    - lensculture
    - myfeatureshoot
    - noicemag
    - oftheafternoon
    - opendoorsgallery
    - organicamag
    - paperjournalmag
    - phroommagazine
    - somewheremagazine
    - subjectivelyobjective
    - yetmagazine
    - yourshotphotographer
  mexico:
    - ilovemexico
    - mejico
    - mexico
    - mexico_amazing
    - mexico_fotos
    - mexico_maravilloso
    - mexicolove
    - mexicomagico
    - mexicomaravilloso
    - vivamexico
  nationalairandspacemuseum:
    - airandspace
  nationalgalleryofart:
    - myngadc
  nationalparks: &nationalparks
    - americasbestidea
    - encuentratuparque
    - findyourpark
    - goparks
    - optoutside
    - nationalparks
  nationalmall: *nationalparks
  yosemitenationalpark: *nationalparks
  greatfallspark: *nationalparks
  grandtetonnationalpark:
    - grandteton
    - grandtetonnationalpark
    - gtnp
    - mygrandteton
    - tetons
  yellowstonenationalpark:
    - yellowstone
    - yellowstonenationalpark
    - yellowstonenps
    - yellowstonepledge
  mountrainiernationalpark:
    - mountrainiernationalpark
    - mountrainiernps
    - mtrainiernationalpark
    - nrthwst
    - ourpnw
    - pnwparadise
    - pnwwilderness
    - wanderwashington
  nationalportraitgallery:
    - mynpg
  newyorkcity: &nyc
    - icapture_nyc
    - igersnyc
    - ilovenyc
    - newyork
    - newyork_ig
    - newyork_instagram
    - newyorkcity
    - newyorkinstagram
    - newyorkphoto
    - nyc
    - nycityworld
    - nyloveyou
    - topnewyorkphoto
  manhattan: *nyc
  brooklyn: *nyc
  queens: *nyc
  bronx: *nyc
  philadelphia:
    - cityofbrotherlylove
    - igers_philly
    - instadelphia
    - instaphilly
    - philadelphia
    - philadelphia_ig
    - philadelphiaphotographer
    - philly_igers
    - phillygram
    - phillylove
    - visitphilly
  pittsburgh:
    - '412'
    - pgh
    - pghcreative
    - pittsburgh
    - pittsburghphotographer
    - pittsburghphotography
    - steelcitygrammers
  seattle:
    - seattle
    - seattle_igers
    - seattlephotographer
    - seattlewashington
    - seattlewa
    - seattlephotography
    - igers_seattle
    - seattlelove
    - exploreseattle
  scotland:
    - igersscotland
    - lovescotland
    - scotland
    - scotland_greatshots
    - scotland_ig
    - scotland_insta
    - scotlandphotography
    - scotlandshots
    - scotshots
  streetphotography:
    - everybodystreet
    - lensculturestreets
    - lensonstreets
    - magnumphotos
    - spicollective
    - storyofthestreet
    - streetgram
    - streetphotography
    - streetphotography_bw
    - streetphotographyinternational
    - streetphotographymagazine
    - streets
    - streetselect
    - streetshooter
    - streetshot
    - thestreetphotographyhub
  tennessee:
    - instagramtennessee
    - tennesseephotographer
    - tennesseephotography
    - tn
  venezuela:
    - elnacionalweb
    - igersvenezuela
    - instavenezuela
    - venezuela
    - vzla
  wildlife:
    - animalplanet
    - bbcearth
    - instawildlife
    - natgeowild
    - naturegrampixels
    - wildlife
    - wildlifeig
    - wildlifeofinstagram
    - wildlifephotographer
    - wildlifephotography
    - wildlifepics
    - wildlifeshots
    - wildlifeshots
    - wildplanet
  wyoming:
    - discover_wyoming
    - explorewyoming
    - thatswy
    - visitwyoming
    - wyoming
    - wyomingexplored
    - wyominglife
    - wyomingphotographer
