instagram:
  fujifilm:
    - fujifilm
    - fujifilm_xseries
    - fuji
    - fujifeed
    - fujixseries
    - myfujifilm
    - fujifilmx_us
    - fujilove
  blackandwhite:
    - bnw
    - bw
    - blackandwhitephotography
    - monochrome
    - bnw_society
    - bnw_captures
    - bnw_life
    - bw_lover
    - blackandwhitephoto
    - bnw_planet
    - monoart
    - blancoynegro
    - bw_photooftheday
    - bw_society
    - instablackandwhite
    - igersbnw
    - monochromatic
    - bnw_demand
    - insta_bw
    - bnwmood
    - bwstyles_gf
    - noiretblanc
  streetphotography:
    - streetphoto
    - streetlife
    - streetphotographers
    - streetphotographer
    - urbanandstreet
    - everybodystreet
    - lensculture
    - ig_street
    - streetlife_award
    - streetshot
    - street_photo_club
    - spicollective
    - lensculturestreets
    - magnumphotos
    - streetart
  scotland:
    - visitscotland
    - instascotland
    - insta_scotland
    - ig_scotland
  districtofcolumbia:
    - districtofcolumbia
    - washingtondc
    - igdc
    - washingtondaily
    - exploredc
    - igersdc
    - walkwithlocals
    - mydccool
    - fotodc
    - dcitystyle
    - acreativedc
    - exposeddc
    - fotodc
  cats:
    - cats
    - catsofinstagram
    - catstagram
    - instacat
    - catlover
    - catoftheday
    - catsagram
    - catlovers
    - ilovemycat
    - cats_of_instagram
    - instagramcats
    - catsofig
    - instacats
  mexico:
    - mexico
    - mextagram
    - mexico_maravilloso
    - mexigers
    - ig_mexico
    - vive_mexico
    - igersmexico
  ciudaddemexico:
    - ciudaddemexico
    - mexicodf
    - mexicocity
    - cdmx
    - df
    - igerscdmx
  newyorkcity:
    - newyorkcity
    - newyork_instagram
    - what_i_saw_in_nyc
    - nycprimeshot
    - instagramnyc
    - ig_nycity
    - ny
    - icapture_nyc
    - made_in_ny
    - newyorknewyork
    - newyork_ig
    - igersofnyc
  landscape:
    - landscape_lovers
    - landscapephotography
    - landscapes
    - landscape_captures
    - landscapelovers
  cityscape:
    - cityscape
    - citylife
    - cityview
    - skyline
    - cityphotography
  architecture:
    - archilovers
    - architecturelovers
    - architectureporn
    - architecturephotography
    - archidaily
    - architexture
    - archdaily
  apple:
    - shotoniphone
  pittsburgh:
    - '412'
    - pgh
    - steelcitygrammers
    - pghcreative
  leica:
    - leica
    - leicacamera
    - leicam
    - leicaphoto
    - leicaphotography
    - 🔴
  caracas:
    - ccs
    - ig_caracas
  venezuela:
    - igersvenezuela
    - vzla
    - elnacionalweb
    - instavenezuela
  nationalgalleryofart:
    - myngadc
  nationalairandspacemuseum:
    - airandspace
  tennessee:
    - instagramtennessee
    - tn
  chattanooga:
    - noogagram
    - nooga
  cars:
    - carporn
    - carsofinstagram
    - carstagram
    - carinstagram
    - instacars
    - igcars
  classiccars:
    - vintagecars
    - retrocars
    - drivetastefully
  film:
    - filmphotography
    - filmisnotdead
    - ishootfilm
    - believeinfilm
    - analogphotography
    - thefilmcommunity
    - shootfilm
  lasvegas:
    - vegas
    - lasvegasstrip
    - vegasbaby
    - sincity
  findyourpark: &parks
    - findyourpark
    - goparks
  nationalparks: *parks
  all:
    - myfeatureshoot
    - somewheremagazine
    - lensculture
tumblr:
  all:
    - 'original photographers'
    - 'photographers on tumblr'
