aliases:
  jacksonhole: &jacksonhole
    - jacksonhole
    - staywild
  nationalparks: &nationalparks
    - americasbestidea
    - encuentratuparque
    - findyourpark
    - goparks
    - nationalparkgeek
    - nationalparks
    - nationalparkservice
    - usinterior
    - usnationalparks
    - nps
  newyorkcity: &nyc
    - igersnyc
    - ilovenyc
    - newyorkinstagram
    - newyorkphoto
    - nycityworld
    - nycspc
    - nyloveyou
    - topnewyorkphoto
  pacificnorthwest: &pacificnorthwest
    - evergreenstate
    - explorepnw
    - livewashington
    - nrthwst
    - pacificnorthwest
    - pnw
    - pnwcollective
    - pnwlife
    - upperleft
    - upperleftusa
    - wanderwashington
    - washingtonexplored
    - washingtonstate
instagram:
  apple:
    - iphonephoto
    - iphonephotograph
    - iphonephotographer
    - iphonephotos
    - iphonepic
    - shotoniphone
  astrophotography:
    - astrophoto
    - astrophotography
    - milkywaychasers
    - nightscape
    - nightscapes
  baldeagle:
    - baldeagle
  baltimore:
    - baltimore
    - bmore
    - charmcity
    - baltimoremd
  blackandwhite:
    - blackandwhitephoto
    - blackandwhitephotography
    - blancoynegro
    - bnw
    - bw
    - igersbnw
    - monochrome
  birds:
    - birding
    - birdphotography
    - birdsofinstagram
    - ornithology
    - wildbirds
  bison:
    - bison
    - americanbison
  caracas:
    - caracas
    - caracascity
    - caracashermosa
    - caracasvenezuela
    - caracaswalk
    - igerscaracas
  cats:
    - cats
    - catsagram
    - catscatscats
    - catsgram
    - catslife
    - catsofig
    - catsofinsta
    - catsofinstagram
    - catstagram
    - catstuff
    - cutecats
    - instacat
    - instacats
    - instagramcats
  chattanooga:
    - chattanooga
    - chattanoogatn
    - chattanoogaphotographer
    - chattanoogatennessee
    - chattanoogaphotography
  cityscapes:
    - cityexplore
    - cityphotography
    - cityscapephotography
    - cityscapes
    - cityscapesphotography
    - cityshots
    - cityskyline
  ciudaddemexico:
    - cdmx
    - ciudaddemexico
    - instacdmx
    - mexicocity
    - mexicodf
  coffee:
    - coffee
    - coffeeholic
    - coffeegram
    - coffeelover
    - coffeelife
    - coffeetime
    - coffeedaily
    - instacoffee
  concerts:
    - bandphotographer
    - concert
    - concertlive
    - concertphotographer
    - concertphotography
    - concertphotos
    - concerts
    - liveconcert
    - liveconcertphotography
    - livemusic
    - livemusicphotography
    - musicphotographer
  districtofcolumbia:
    - dcfocused
    - dcitystyle
    - dclife
    - districtofcolumbia
    - exploredc
    - fotodc
    - ilovedc
    - mydccool
    - thedistrict
    - walkwithlocals
    - washingtondaily
    - washingtondc
    - washmagphoto
  dogs:
    - cutedogs
    - doggy
    - doglifestyle
    - dogs
    - dogsofig
    - dogsofinstagram
    - dogstagram
    - dogstagram
    - igdogs
    - ilovedogs
    - instadogs
  enumclaw: *pacificnorthwest
  featureaccounts:
    - aperturefoundation
    - lensculturediscovery
  film:
    - analogphoto
    - believeinfilm
    - filmisnotdead
    - filmphotography
    - grainisgood
    - onfilm
    - shootfilm
    - shotonfilm
  fujifilm:
    - fujifeed
    - fujifilm
    - fujilove
    - fujix
    - fujixseries
  grizzlybears:
    - grizzly
    - grizzlybear
    - grizzlybears
  landscapes:
    - landscapecaptures
    - landscapephoto
    - landscapephotography
    - landscapephotomag
    - landscapeporn
    - landscapes
    - outdoorphotomag
  lasvegas:
    - lasvegasstrip
    - sincity
    - vegas
    - vegasbaby
  leica:
    - 🔴
    - leica
    - leicacamera
    - leicagram
    - leicam
    - leicaphoto
    - leicaphotography
    - leicaworld
  londonbridgestudio:
    - *pacificnorthwest
    - grunge
    - makemusic
    - music
    - musicstudio
    - pearljam
    - recordingstudio
  longexposure:
    - longexpo
    - longexposure
    - longexposurephotography
    - longexposureshots
  mexico:
    - ilovemexico
    - mejico
    - mexico
    - mexicolove
    - mexicomagico
    - mexicomaravilloso
    - vivamexico
  mobile:
    - mobilephotography
    - phonephotography
    - phoneshot
    - phoneographic
    - phoneography
    - phonephoto
  nationalairandspacemuseum:
    - airandspace
  nationalelkrefuge: *jacksonhole
  nationalgalleryofart:
    - myngadc
  nationalparks: *nationalparks
  nationalmall: *nationalparks
  yosemitenationalpark: *nationalparks
  greatfallspark: *nationalparks
  grandtetonnationalpark:
    - grandteton
    - grandtetonnationalpark
    - gtnp
    - mygrandteton
    - tetons
  yellowstonenationalpark:
    - yellowstone
    - yellowstonenationalpark
    - yellowstonenps
    - yellowstonepledge
    - yellowstoneforever
    - ynp
  mountrainiernationalpark:
    - *pacificnorthwest
    - mountrainiernationalpark
    - mountrainiernps
    - mtrainiernationalpark
  nationalportraitgallery:
    - mynpg
  manhattan: *nyc
  brooklyn: *nyc
  queens: *nyc
  bronx: *nyc
  pearljam:
    - music
    - pearljam
    - rock
    - rockband
    - rockmusic
    - rocknroll
    - rockphotographer
  philadelphia:
    - cityofbrotherlylove
    - instadelphia
    - instaphilly
    - philadelphia
    - philadelphiaphotographer
    - phillygram
    - phillylove
    - visitphilly
  pittsburgh:
    - '412'
    - pgh
    - pghcreative
    - pittsburgh
    - pittsburghphotographer
    - pittsburghphotography
    - steelcitygrammers
  recordstore:
    - music
    - records
    - recordshop
    - recordstore
    - vinyladdict
    - vinylcommunity
    - vinylgram
    - vinyligclub
    - vinyljunkies
    - vinyllove
    - vinylmusic
    - vinylrecords
  sanfrancisco:
    - alwayssf
    - citybythebay
    - igerssf
    - igsanfrancisco
    - onlyinsf
    - sanfrancisco
    - sf
    - streetsofsf
  seattle:
    - *pacificnorthwest
    - exploreseattle
    - seattle
    - seattlelife
    - seattlelove
    - seattlephotographer
    - seattlephotography
    - seattlewa
    - seattlewashington
    - visitseattle
  scotland:
    - igersscotland
    - lovescotland
    - scotland
    - scotlandphotography
    - scotlandshots
    - scotshots
  streets:
    - dc_spc
    - everybodystreet
    - lensculturestreets
    - lensonstreets
    - myspc
    - spicollective
    - storyofthestreet
    - streetgram
    - streetphotography
    - streetphotographyinternational
    - thestreetphotographyhub
  tacoma:
    - *pacificnorthwest
    - tacomawashington
  tennessee:
    - instagramtennessee
    - tennesseephotographer
    - tennesseephotography
    - tn
  venezuela:
    - elnacionalweb
    - igersvenezuela
    - instavenezuela
    - venezuela
    - vzla
  wildlife:
    - animalplanet
    - bbcearth
    - outdoorphotomag
    - wildlifephotographer
    - wildlifephotography
    - wildlifeplanet
  wyoming:
    - explorewyoming
    - thatswy
    - visitwyoming
    - wyoming
    - wyomingexplored
    - wyominglife
    - wyomingphotographer
