instagram:
  fujifilm:
    - fujifeed
    - fujifilmx_us
    - fujilove
    - fujifilm_xseries
  streetphotography:
    - spicollective
    - ig_street
    - everybodystreet
  districtofcolumbia:
    - igdc
  all:
    - myfeatureshoot
    - somewheremagazine
