instagram:
  apple:
    - iphoneography
    - iphoneonly
    - iphonephotography
    - shotoniphone
  architecture:
    - archdaily
    - archidaily
    - archilovers
    - architecturelovers
    - architecturephotography
    - architectureporn
    - architexture
  caracas:
    - ccs
    - ig_caracas
  cars:
    - carinstagram
    - carporn
    - carsofinstagram
    - carstagram
    - igcars
    - instacars
  cats:
    - animalsofinstagram
    - cat_features
    - catlove
    - catlover
    - catlovers
    - catoftheday
    - cats_of_instagram
    - cats_of_world
    - catsagram
    - catsofig
    - catsofinstagram
    - catstagram
    - caturday
    - catvalentine
    - catwalk
    - cutecat
    - ilovemycat
    - instacat
    - instacats
    - instagramcats
    - katze
    - kitten
    - kittylove
    - lovecats
    - meow
  chattanooga:
    - nooga
    - noogagram
  cityscape:
    - citylife
    - cityphotography
    - cityscape
    - cityview
    - skyline
  ciudaddemexico:
    - cdmx
    - ciudaddemexico
    - df
    - igerscdmx
    - mexicocity
    - mexicodf
  classiccars:
    - drivetastefully
    - retrocars
    - vintagecars
  concert:
    - livemusic
    - rocknroll
    - concertphoto
    - livephotography
    - musiclife
    - rockphotography
    - concertphotography
    - musicphotography
    - musicphoto
    - livemusicphotography
    - concertphotographer
    - bandphotographer
    - musicphotographer
    - concertphotos
    - livemusicphotographer
    - liveconcertphotography
  districtofcolumbia:
    - acreativedc
    - dcitystyle
    - districtofcolumbia
    - exploredc
    - exposeddc
    - fotodc
    - igdc
    - igersdc
    - mydccool
    - streetmeetdc
    - walkwithlocals
    - washingtondaily
    - washingtondc
  dogs:
    - barkbox
    - bestwoof
    - dog_features
    - doglife
    - doglover
    - doglovers
    - dogoftheday
    - dogs_of_instagram
    - dogscorner
    - dogslife
    - dogsofig
    - instagramdogs
    - instapet
    - lovepuppies
    - petsagram
    - petsofinstagram
    - petstagram
    - pup
    - puppies
    - puppiesofinstagram
    - puppylove
    - weeklyfluff
  film:
    - analogphotography
    - believeinfilm
    - filmisnotdead
    - filmphotography
    - ishootfilm
    - shootfilm
    - thefilmcommunity
  findyourpark: &findyourpark
    - findyourpark
    - goparks
  fujifilm:
    - fuji
    - fujifeed
    - fujifilm
    - fujifilm_xseries
    - fujifilmx_us
    - fujifilmxseries
    - fujilove
    - fujixclub
    - fujixseries
    - myfujifilm
  landscape:
    - landscape_captures
    - landscape_lovers
    - landscapelovers
    - landscapephotography
    - landscapes
  lasvegas:
    - lasvegasstrip
    - sincity
    - vegas
    - vegasbaby
  leica:
    - 🔴
    - leica
    - leicacamera
    - leicam
    - leicaphoto
    - leicaphotography
  magazines:
    - lensculture
    - myfeatureshoot
    - somewheremagazine
    - noicemag
    - paperjournalmag
    - archivecollectivemag
    - subjectivelyobjective
    - yetmagazine
    - burnmagazine
    - aperturefoundation
    - phroommagazine
    - oftheafternoon
    - ifyouleave
    - gupmagazine
    - foammagazine
    - organicamag
    - aintbadmagazine
    - opendoorsgallery
  mexico:
    - ig_mexico
    - igersmexico
    - mexico
    - mexico_maravilloso
    - mexigers
    - mextagram
    - vive_mexico
  nationalairandspacemuseum:
    - airandspace
  nationalgalleryofart:
    - myngadc
  nationalparks: *findyourpark
  newyorkcity: &nyc
    - icapture_nyc
    - ig_great_shots_nyc
    - ig_nycity
    - igersofnyc
    - instagramnyc
    - made_in_ny
    - newyork_ig
    - newyork_instagram
    - newyorkcity
    - newyorknewyork
    - ny
    - nycprimeshot
    - unlimitednewyork
    - what_i_saw_in_nyc
  manhattan: *nyc
  brooklyn: *nyc
  queens: *nyc
  bronx: *nyc
  philadelphia:
    - discoverphl
    - explore215
    - explorephilly
    - igers_philly
    - igersphilly
    - instadelphia
    - instaphilly
    - philadelphia
    - philly
    - phillygram
    - phillyigers
    - phillylove
    - phillyprimeshots
    - phl
    - visitphilly
    - whyilovephilly
  pittsburgh:
    - '412'
    - pgh
    - pghcreative
    - steelcitygrammers
  scotland:
    - ig_scotland
    - insta_scotland
    - instascotland
    - visitscotland
  streetphotography:
    - everybodystreet
    - ig_street
    - lensculture
    - lensculturestreets
    - magnumphotos
    - seemycity
    - spicollective
    - street_photo_club
    - streetart
    - streetlife
    - streetlife_award
    - streetmagazine
    - streetmagazines
    - streetphoto
    - streetphotographer
    - streetphotographers
    - streets_vision
    - streetshot
    - urbanandstreet
  tennessee:
    - instagramtennessee
    - tn
  venezuela:
    - elnacionalweb
    - igersvenezuela
    - instavenezuela
    - vzla
