common: &default_settings
  license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  app_name: <%= ENV["HEROKU_APP_NAME"] %>
  log_level: info
development:
  <<: *default_settings
  app_name: <%= ENV["HEROKU_APP_NAME"] %> (Development)
test:
  <<: *default_settings
  monitor_mode: false
staging:
  <<: *default_settings
  app_name: <%= ENV["HEROKU_APP_NAME"] %> (Staging)
production:
  <<: *default_settings
  
