entry:
  srcset:
    - 640x0
    - 960x0
    - 1136x0
    - 750x0
    - 1334x0
    - 1242x0
    - 2208x0
    - 1024x0
    - 768x0
    - 2048x0
    - 1152x0
    - 1536x0
    - 1280x0
    - 1440x0
    - 2560x0
    - 2880x0
    - 1920x0
    - 3840x0
  sizes:
    - "(min-width: 1920px) 1920px"
    - 100vw
  filters:
    - "no_upscale()"
    - "quality(90)"
entry_list_item:
  srcset:
    - 308x308
    - 363x363
    - 603x603
    - 336x336
    - 251x251
    - 672x672
    - 502x502
    - 758x758
    - 422x422
    - 844x844
    - 355x355
    - 710x710
    - 475x475
    - 950x950
  sizes:
    - "(min-width: 1920px) 475px"
    - "(min-width: 1440px) calc((100vw - 20px)/4)"
    - "(min-width: 600px) calc((100vw - 16px)/3)"
    - calc((100vw - 12px)/2)
  filters:
    - "quality(75)"
    - "strip_icc()"
admin_entry:
  srcset:
    - 800x0
    - 1600x0
  sizes:
    - "(min-width: 840px) 800px"
    - calc(100vw - 40px)
  filters:
    - "quality(90)"
admin_edit:
  srcset:
    - 300x0
    - 600x0
    - 900x0
  sizes:
    - 300px
  filters:
    - "no_upscale()"
    - "quality(90)"
