entry:
  srcset:
    - 640x0
    - 960x0
    - 1136x0
    - 750x0
    - 1334x0
    - 1242x0
    - 2208x0
    - 1024x0
    - 768x0
    - 2048x0
    - 1152x0
    - 1536x0
    - 1280x0
    - 1440x0
    - 2560x0
    - 2880x0
    - 1920x0
    - 3840x0
  sizes:
    - "(min-width: 1920px) 1920px"
    - 100vw
  filters:
    - "no_upscale()"
    - "quality(90)"
entry_list_item:
  srcset:
    - 296x0
    - 544x0
    - 351x0
    - 424x0
    - 585x0
    - 705x0
    - 662x0
    - 490x0
    - 746x0
    - 310x0
    - 620x0
  sizes:
    - "(min-width: 1280px) 310px"
    - "(min-width: 600px) calc((100vw - 32px)/3)"
    - calc((100vw - 24px)/2)
  filters:
    - "no_upscale()"
    - "quality(90)"
admin_entry:
  srcset:
    - 800x0
    - 1600x0
  sizes:
    - "(min-width: 840px) 800px"
    - calc(100vw - 40px)
  filters:
    - "quality(90)"
admin_edit:
  srcset:
    - 300x0
    - 600x0
    - 900x0
  sizes:
    - 300px
  filters:
    - "no_upscale()"
    - "quality(90)"
