entry: &entry
  src: 1440
  srcset:
    - 640
    - 1136
    - 750
    - 1334
    - 1242
    - 2208
    - 1125
    - 2436
    - 2048
    - 1536
    - 2224
    - 1668
    - 2732
    - 2880
    - 3360
    - 2560
    - 2880
  sizes:
    - "(min-width: 1680px) 1680px"
    - 100vw
entry_list_item: &entry_list_item
  src: 355
  srcset:
    - 320
    - 378
    - 376
    - 444
    - 414
    - 735
    - 564
    - 813
    - 682
    - 512
    - 740
    - 556
    - 682
    - 720
    - 840
    - 640
    - 720
  sizes:
    - "(min-width: 1680px) 420px"
    - "(min-width: 1280px) 25vw"
    - "(min-width: 400px) calc(100vw/3)"
    - 50vw
related_item:
  <<: *entry_list_item
  square: Yes
admin_entry:
  <<: *entry
  sizes:
    - "(min-width: 840px) 840px"
    - 100vw
admin_edit:
  src: 300
  srcset:
    - 300
    - 516
    - 600
    - 626
    - 900
    - 1056
    - 1412
  sizes:
    - "(min-width: 800px) 300px"
    - calc(100vw - 60px)
map:
  src: 300
  srcset:
    - 300
    - 600
    - 900
  sizes:
    - 300px
  square: Yes
  auto: 'format,compress'
