entry:
  srcset:
    - 640
    - 960
    - 1136
    - 750
    - 1334
    - 1242
    - 2208
    - 1024
    - 768
    - 2048
    - 1152
    - 1536
    - 1280
    - 1440
    - 2560
    - 2880
    - 1920
    - 3840
  sizes:
    - "(min-width: 1920px) 1920px"
    - 100vw
  quality: 90
entry_list_item:
  srcset:
    - 308
    - 363
    - 603
    - 336
    - 251
    - 672
    - 502
    - 758
    - 422
    - 844
    - 355
    - 710
    - 475
    - 950
  sizes:
    - "(min-width: 1920px) 475px"
    - "(min-width: 1440px) calc((100vw - 20px)/4)"
    - "(min-width: 600px) calc((100vw - 16px)/3)"
    - calc((100vw - 12px)/2)
  quality: 50
  square: Yes
admin_entry:
  srcset:
    - 800
    - 1600
  sizes:
    - "(min-width: 840px) 800px"
    - calc(100vw - 40px)
  quality: 60
admin_edit:
  srcset:
    - 300
    - 600
    - 900
  sizes:
    - 300px
  quality: 60
