entry:
  src: 1440
  srcset:
    - 640
    - 960
    - 1136
    - 750
    - 1334
    - 1242
    - 2208
    - 1024
    - 768
    - 2048
    - 1152
    - 1536
    - 1280
    - 1440
    - 2560
    - 2732
    - 2880
  sizes:
    - "(min-width: 1440px) 1440px"
    - 100vw
  quality: 90
  client_hints: "Width,DPR"
entry_list_item:
  src: 475
  srcset:
    - 308
    - 363
    - 603
    - 336
    - 251
    - 672
    - 502
    - 758
    - 422
    - 844
    - 355
    - 710
    - 900
  sizes:
    - "(min-width: 1440px) 355px"
    - "(min-width: 600px) calc((100vw - 16px)/3)"
    - calc((100vw - 12px)/2)
  quality: 50
  square: Yes
admin_entry:
  src: 800
  srcset:
    - 800
    - 1122
    - 1600
  sizes:
    - "(min-width: 840px) 800px"
    - calc(100vw - 40px)
  quality: 60
admin_edit:
  src: 300
  srcset:
    - 300
    - 600
    - 900
    - 1056
  sizes:
    - "(min-width: 800px) 300px"
    - calc(100vw - 60px)
  quality: 60
