:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  :schedule:
    publish_queued_entries:
      cron: '0 0 * * * *'   # Runs every hour
      class: PublishWorker
      queue: high
      description: "Attempts to publish a queued entry every hour."
    random_bluesky:
      cron: '0 12,14,16,18 * * *'
      class: RandomBlueskyWorker
      queue: high
      description: "Shares a random photo on Bluesky."
    random_mastodon:
      cron: '0 12 * * *'
      class: RandomMastodonWorker
      queue: high
      description: "Shares a random photo on Mastodon."
    random_tumblr:
      cron: '0 12,14,16,18 * * *'
      class: RandomTumblrWorker
      queue: high
      description: "Shares a random photo on Tumblr."
