:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  publish_queued_entries:
    cron: '0 0 * * * *'   # Runs every hour
    class: PublishWorker
    queue: high
    description: "Attempts to publish a queued entry every hour."
