:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  :schedule:
    publish_queued_entries:
      cron: '0 0 * * * *'   # Runs every hour
      class: PublishWorker
      queue: high
      description: "Attempts to publish a queued entry every hour."
    share_random_photo:
      cron: '0 14 * * *'
      class: RandomShareWorker
      queue: high
      description: "Shares a random photo every day."
