:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  :schedule:
    publish_queued_entries:
      cron: '0 0 * * * *'   # Runs every hour
      class: PublishWorker
      queue: high
      description: "Attempts to publish a queued entry every hour."
    random_bluesky_landscape:
      cron: '0 14 * * *'
      class: RandomShareWorker
      queue: high
      keyword_argument: true
      args: { tag: 'Landscapes', platform: 'Bluesky' }
      description: "Shares a random landscape photo on Bluesky."
    random_bluesky_wildlife:
      cron: '0 18 * * *'
      class: RandomShareWorker
      queue: high
      keyword_argument: true
      args: { tag: 'Wildlife', platform: 'Bluesky' }
      description: "Shares a random wildlife photo on Bluesky."
    random_mastodon_landscape:
      cron: '0 14 * * *'
      class: RandomShareWorker
      queue: high
      keyword_argument: true
      args: { tag: 'Landscapes', platform: 'Mastodon' }
      description: "Shares a random landscape photo on Mastodon."
    random_mastodon_wildlife:
      cron: '0 18 * * *'
      class: RandomShareWorker
      queue: high
      keyword_argument: true
      args: { tag: 'Wildlife', platform: 'Mastodon' }
      description: "Shares a random wildlife photo on Mastodon."
    random_tumblr_landscape:
      cron: '0 14 * * *'
      class: RandomShareWorker
      queue: high
      keyword_argument: true
      args: { tag: 'Landscapes', platform: 'Tumblr' }
      description: "Shares a random landscape photo on Mastodon."
    random_tumblr_wildlife:
      cron: '0 18 * * *'
      class: RandomShareWorker
      queue: high
      keyword_argument: true
      args: { tag: 'Wildlife', platform: 'Tumblr' }
      description: "Shares a random wildlife photo on Tumblr."
